/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Archive`; params?: Router.UnknownInputParams; } | { pathname: `/Classes`; params?: Router.UnknownInputParams; } | { pathname: `/Contacts`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/Homework`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Archive`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Contacts`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Homework`; params?: Router.UnknownInputParams; } | { pathname: `/ParentUserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/TestScore`; params?: Router.UnknownInputParams; } | { pathname: `/UserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Archive`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes`; params?: Router.UnknownOutputParams; } | { pathname: `/Contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/Homework`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Parent-Archive`; params?: Router.UnknownOutputParams; } | { pathname: `/Parent-Contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/Parent-Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Parent-Homework`; params?: Router.UnknownOutputParams; } | { pathname: `/ParentUserProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/SignupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/TestScore`; params?: Router.UnknownOutputParams; } | { pathname: `/UserProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Archive${`?${string}` | `#${string}` | ''}` | `/Classes${`?${string}` | `#${string}` | ''}` | `/Contacts${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/Homework${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Parent-Archive${`?${string}` | `#${string}` | ''}` | `/Parent-Contacts${`?${string}` | `#${string}` | ''}` | `/Parent-Dashboard${`?${string}` | `#${string}` | ''}` | `/Parent-Homework${`?${string}` | `#${string}` | ''}` | `/ParentUserProfile${`?${string}` | `#${string}` | ''}` | `/SignupScreen${`?${string}` | `#${string}` | ''}` | `/TestScore${`?${string}` | `#${string}` | ''}` | `/UserProfile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Archive`; params?: Router.UnknownInputParams; } | { pathname: `/Classes`; params?: Router.UnknownInputParams; } | { pathname: `/Contacts`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/Homework`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Archive`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Contacts`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Parent-Homework`; params?: Router.UnknownInputParams; } | { pathname: `/ParentUserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/TestScore`; params?: Router.UnknownInputParams; } | { pathname: `/UserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
